### ISSUE TITLE
강의 환경세팅 맞추기

### ISSUE THREAD

**Issue by teang1995** [teang1995/movie_review_project#5]
강의 환경 세팅 맞추는 거 편하게 따라오게 해주는 이슈

**Comment by teang1995** [comment]
1. 자바 11 설치
[link](https://www.oracle.com/kr/java/technologies/javase/jdk11-archive-downloads.html)

**Comment by teang1995** [comment]
3. springboot 사이트로 이동 후 아래 설정에 맞춰 프로젝트 선택
[link](https://start.spring.io/)
```yaml
Project : Gradle Project
SpringBoot: 2.6.6
Language:  Java
Packaging: Jar
Java: 11
groupId: hello
artifactid: hello-spring
Dependencies: Spring Web, Thymeleaf
```
